language: scala
scala:
   - 2.11.8
jdk:
  - oraclejdk8

services:
  - docker
  
before_script:
  - npm install -g bower
  - bower install

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script: sbt test 'project visualization' 'docker:publish'